name: Grade Assignment 3

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  validateAssignment:
    uses: CamBamClasses/ValidateAssignment/.github/workflows/ValidateAssignment.yml@padawan
    with:
      assignmentNum: 3
      cleanRepoScore: 0
      submitWithGithubScore: 0
      scores: 8 8 8 9 3 3 3 8
      testType: files
      withCmake: false
      incompletePoints: 0
